#!/bin/bash

source "$(dirname "$BASH_SOURCE")/shared/filter"
source "$(dirname "$BASH_SOURCE")/shared/table"

BASE_URL=https://www.strava.com/api/v3

page=1

main() {
  parse_args $*

  list | filter_many | table
}

parse_args() {
  while getopts ":p:" opt; do
    case $opt in
      p) page="$OPTARG" ;;
      \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
      :) echo "Option -$OPTARG requires an argument" >&2; exit 1 ;;
    esac
  done
}

list() {
  local access_token=$(< .access-token)
  curl -G -s $BASE_URL/athlete/activities -H "Authorization: Bearer $access_token" -d page=$page
}

main $*

