#!/bin/bash

source "$(dirname "$BASH_SOURCE")/shared/filter"
source "$(dirname "$BASH_SOURCE")/shared/gear"
source "$(dirname "$BASH_SOURCE")/shared/request"
source "$(dirname "$BASH_SOURCE")/shared/table"

page=1

main() {
  parse_args $*

  local gear=$(list_gear)
  list | filter_activity $gear | table
}

parse_args() {
  while getopts ":p:" opt; do
    case $opt in
      p) page="$OPTARG" ;;
      \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
      :) echo "Option -$OPTARG requires an argument" >&2; exit 1 ;;
    esac
  done
}

list() {
  request "/athlete/activities" "-G -d page=$page"
}

main $*

