#!/bin/bash

source "$(dirname "$BASH_SOURCE")/shared/filter"
source "$(dirname "$BASH_SOURCE")/shared/request"
source "$(dirname "$BASH_SOURCE")/shared/table"

main() {
  parse_args $*

  update | filter_one | table
}

parse_args() {
  while getopts ":n:g:p:" opt; do
    case $opt in
      n) name="$OPTARG" ;;
      g) gear_id="$OPTARG" ;;
      p) private="$OPTARG" ;;
      \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
      :) echo "Option -$OPTARG requires an argument" >&2; exit 1 ;;
    esac
  done

  shift $((OPTIND -1))
  activity_id=$1
}

update() {
  local options=("-X PUT")
  if [[ -n "$name" ]]; then options+=("-F name=$name"); fi
  if [[ -n "$gear_id" ]]; then options+=("-F gear_id=$gear_id"); fi
  if [[ -n "$private" ]]; then options+=("-F private=$private"); fi

  request "/activities/$activity_id" "${options[*]}"
}

main $*

