#!/bin/bash

source "$(dirname "$BASH_SOURCE")/shared/filter"
source "$(dirname "$BASH_SOURCE")/shared/gear"
source "$(dirname "$BASH_SOURCE")/shared/request"
source "$(dirname "$BASH_SOURCE")/shared/table"

main() {
  parse_args $*

  local gear=$(list_gear)
  update | filter_activity $gear | table
}

parse_args() {
  while getopts ":n:t:g:p:" opt; do
    case $opt in
      n) name="$OPTARG" ;;
      t) type="$OPTARG" ;;
      g) gear_id="$OPTARG" ;;
      p) private="$OPTARG" ;;
      \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
      :) echo "Option -$OPTARG requires an argument" >&2; exit 1 ;;
    esac
  done

  shift $((OPTIND -1))
  activity_ids=$*
}

update() {
  local options=("-X PUT")
  if [[ -n "$name" ]]; then options+=("-F name=$name"); fi
  if [[ -n "$type" ]]; then options+=("-F type=$type"); fi
  if [[ -n "$gear_id" ]]; then options+=("-F gear_id=$gear_id"); fi
  if [[ -n "$private" ]]; then options+=("-F private=$private"); fi

  local updated=()
  for activity_id in $activity_ids; do
    updated+=("$(request "/activities/$activity_id" "${options[*]}")")
  done
  echo "[" $(join_by , "${updated[@]}") "]"
}

join_by() {
  local IFS="$1"
  shift
  echo "$*"
}

main $*

