#!/bin/bash

source "$(dirname "$BASH_SOURCE")/shared/filter"
source "$(dirname "$BASH_SOURCE")/shared/gear"
source "$(dirname "$BASH_SOURCE")/shared/request"
source "$(dirname "$BASH_SOURCE")/shared/table"

main() {
  parse_args "$@"

  local gear=$(list_gear)
  update | filter_activity $gear | table
}

parse_args() {
  while getopts ":n:t:g:p:" opt; do
    case $opt in
      n) name="$OPTARG" ;;
      t) type="$OPTARG" ;;
      g) gear_id="$OPTARG" ;;
      p) private="$OPTARG" ;;
      \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
      :) echo "Option -$OPTARG requires an argument" >&2; exit 1 ;;
    esac
  done

  shift $((OPTIND -1))
  activity_ids=$*
}

update() {
  local options=("-X PUT")
  if [[ -n "$name" ]]; then options+=("--data-urlencode \"name=$name\""); fi
  if [[ -n "$type" ]]; then options+=("-d type=$type"); fi
  if [[ -n "$gear_id" ]]; then options+=("-d gear_id=$gear_id"); fi
  if [[ -n "$private" ]]; then options+=("-d private=$private"); fi

  local updated=()
  for activity_id in $activity_ids; do
    read current_private <<<$(get_default_flags ${activity_id})
    if [[ -z "$private" ]]; then options+=("-d private=$current_private"); fi
    updated+=("$(request "/activities/$activity_id" "${options[*]}")")
  done
  echo "[" $(join_by , "${updated[@]}") "]"
}

get_default_flags() {
  local activity_id=$1
  request "/activities/$activity_id -X GET" | jq -r '"\(.private)"'
}

join_by() {
  local IFS="$1"
  shift
  echo "$*"
}

main "$@"

