#!/bin/bash

filter_one() {
  local jq_filter='[.id, .start_date_local, .name, .distance, .gear_id, .private] | map(tostring) | @tsv'
  jq -r "$jq_filter"
}

filter_many() {
  local jq_filter='.[] | [.id, .start_date_local, .name, .distance, .gear_id, .private] | map(tostring) | @tsv'
  jq -r "$jq_filter"
}

