#!/bin/bash

table() {
  local activities=$(< /dev/stdin)
  local widths=$(max_lengths "$activities")
  format_activities "$activities" "$widths"
}

max_lengths() {
  local activities=$1
  echo "$activities" | gawk '
BEGIN { FS = "\t" }
{
  for (i = 1; i <= NF; i++) {
    max[i] = (length($i) > max[i] ? length($i) : max[i])
  }
}
END {
  for (i = 1; i <= NF; i++) {
    printf "%d%s", max[i], (i == NF ? RS : FS)
  }
}
'
}

format_activities() {
  local actitivies=$1
  local widths=$2
  echo "$activities" | gawk -v widths="$widths" '
BEGIN {
  FS = "\t"

  split(widths, col_widths, FS)
  id_width = col_widths[1]
  start_date_width = 16
  type_width = col_widths[3]
  name_width = col_widths[4]
  distance_width = col_widths[5]
  gear_id_width = max(col_widths[6], 7)
  gear_name_width = max(col_widths[7], 9)
  private_width = 1

  print_header()
}
{
  id = $1
  start_date = format_date($2)
  type = $3
  name = $4
  distance_km = to_km($5)
  gear_id = $6
  gear_name = $7
  private = ($8 == "true" ? "+" : " ")

  printf "%*s", id_width, id
  printf " "
  printf "%s", start_date
  printf " "
  printf "%-*s", type_width, type
  printf " "
  printf "%-*s", name_width, name
  printf " "
  printf "%*.l3f", distance_width, distance_km
  printf " "
  printf "%-*s", gear_id_width, gear_id
  printf " "
  printf "%-*s", gear_name_width, gear_name
  printf " "
  printf "%s", private
  printf "\n"
}

function print_header() {
  printf "%-*s", id_width, "id"
  printf " "
  printf "%-*s", start_date_width, "start date"
  printf " "
  printf "%-*s", type_width, "type"
  printf " "
  printf "%-*s", name_width, "name"
  printf " "
  printf "%-*s", distance_width, "km"
  printf " "
  printf "%-*s", gear_id_width, "gear id"
  printf " "
  printf "%-*s", gear_name_width, "gear name"
  printf " "
  printf "%-*s", private_width, "p"
  printf "\n"

  repeat("-", id_width)
  printf " "
  repeat("-", start_date_width)
  printf " "
  repeat("-", type_width)
  printf " "
  repeat("-", name_width)
  printf " "
  repeat("-", distance_width)
  printf " "
  repeat("-", gear_id_width)
  printf " "
  repeat("-", gear_name_width)
  printf " "
  repeat("-", private_width)
  printf "\n"
}

function repeat(str, times) {
  for (i = 0; i < times; i++) printf str
}

function max(a, b) {
  return a > b ? a : b
}

function format_date(date) {
  sub(/T/, " ", date)
  sub(/Z/, "", date)
  sub(/:[0-9]{2}$/, "", date)
  return date
}

function to_km(distance) {
  return distance / 1000
}
'
}
